frontend_backend_projects/django_project/homework/project/urls.py
from django.urls import re_path, path
from . import views

app_name = 'project'
urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^register/$', views.register, name='register'), 
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^logout/$', views.logout, name='logout'), 
    re_path(r'^user/(?P<pk>\d+)/profile/$', views.profile, name='profile'), 
    re_path(r'^user/(?P<pk>\d+)/profile/update/$', views.profile_update, 
            name='profile_update'), 
    re_path(r'user/(?P<pk>\d+)/pwdchange/$', views.pwd_change, 
            name='pwd_change'), 
]

frontend_backend_projects/django_project/homework/project/templates/project/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="renderer" content="webkit" />
    <title>作业管理系统- 主页</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <!--[if lt IE 9]>
      <meta http-equiv="refresh" content="0;ie.html" />
    <![endif]-->
    <link rel="shortcut icon" href="favicon.ico" />
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet" />
    <link href="{% static '/css/animate.css' %}" rel="stylesheet" />
    <link href="{% static '/css/style.css' %}" rel="stylesheet" />
    <link
      href="{% static '/css/plugins/footable/footable.core.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static '/css/plugins/iCheck/custom.css' %}"
      rel="stylesheet"
    />
    <!-- Global js -->
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static '/js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static '/js/plugins/layer/layer.min.js' %}"></script>
    <script src="{% static '/js/plugins/footable/footable.all.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static '/js/plugins/iCheck/icheck.min.js' %}"></script>
    <!-- Peity -->
    <script src="{% static '/js/plugins/peity/jquery.peity.min.js' %}"></script>
    <script src="{% static '/js/hAdmin.js' %}"></script>
    <script src="{% static '/js/index.js' %}"></script>
    <script src="{% static '/js/content.js' %}"></script>
    <script src="{% static '/js/plugins/pace/pace.min.js' %}"></script>
    <!-- Peity -->
    <script src="{% static '/js/demo/peity-demo.js' %}"></script>
    <!-- ECharts -->
    <script src="{% static 'js/plugins/echarts/echarts-all.js' %}"></script>
  </head>
  {% block content %} {% endblock %}
</html>

frontend_backend_projects/django_project/homework/project/templates/project/index.html
{% extends "project/base.html" %} 
{% block content %}
<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
  <div id="wrapper">
    <!--Left Navigation Start-->
    <nav class="navbar-default navbar-static-side" role="navigation">
      <div class="nav-close"><i class="fa fa-times-circle"></i></div>
      <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
          <li class="nav-header">
            <div class="dropdown profile-element">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <span class="clear">
                  <span class="block m-t-xs" style="font-size:20px;">
                    <strong class="font-bold">作业管理系统</strong>
                  </span>
                </span>
              </a>
            </div>
            <div class="logo-element">作业管理系统</div>
          </li>
          <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
            <span class="ng-scope">&nbsp;</span>
          </li>
          <li>
            <a class="J_menuItem" href="#">
              <i class="fa fa-home"></i>
              <span class="nav-label">主页</span>
            </a>
          </li>
          <li class="line dk"></li>
          <li>
            <a href="#"
              ><i class="glyphicon glyphicon-user"></i>
              <span class="nav-label">个人资料</span
              ><span class="fa arrow"></span
            ></a>
            <ul class="nav nav-second-level">
              <li>
                <a class="J_menuItem" href="{% url 'project:profile' request.user.id %}">
                  查看资料
                </a>
              </li>
              <li>
                <a class="J_menuItem" href="{% url 'project:pwd_change' request.user.id %}">
                  修改密码
                </a>
              </li>
            </ul>
          </li>
          <li class="line dk"></li>
          <li>
            <a href="#"
              ><i class="glyphicon glyphicon-book"></i>
              <span class="nav-label">课程管理</span
              ><span class="fa arrow"></span
            ></a>
            <ul class="nav nav-second-level">
              <li><a class="J_menuItem" href="#">全部课程</a></li>
              <li><a class="J_menuItem" href="#">我的课程</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
    <!--Left Navigation End-->
    <!--Right Navigation Start-->
    <div id="page-wrapper" class="gray-bg dashbard-1">
      <div class="row border-bottom">
        <nav
          class="navbar navbar-static-top"
          role="navigation"
          style="margin-bottom: 0"
        >
          <div class="navbar-header">
            <a
              class="navbar-minimalize minimalize-styl-2 btn btn-info "
              href="#"
              ><i class="fa fa-bars"></i>
            </a>
            <form
              role="search"
              class="navbar-form-custom"
              method="get"
              action=""
            >
              {% csrf_token %}
              <div class="form-group">
                <input
                  type="text"
                  placeholder="搜索通知标题或内容 …"
                  class="form-control"
                  name="q"
                  id="q"
                />
              </div>
            </form>
          </div>
          <ul class="nav navbar-top-links navbar-right">
            {% if request.user.is_authenticated %}
            <li class="dropdown">
              <a
                class="dropdown-toggle btn-green"
                data-toggle="dropdown"
                href="#"
              >
                <span class="glyphicon glyphicon-user"></span> {{
                request.user.username }} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li class="m-t-xs">
                  <a href="{% url 'project:logout' %}"
                    ><span class="glyphicon glyphicon-log-out"></span
                    >&nbsp;&nbsp;退出登录
                  </a>
                </li>
              </ul>
            </li>
            {% else %}
            <li class="dropdown">
              <a class="dropdown-toggle btn-green" href="/register">
                <span class="glyphicon glyphicon-user"></span> 注册
              </a>
            </li>
            <li class="dropdown">
              <!-- 硬编码路由 -->
              <a class="dropdown-toggle" href="/login">
                <span class="glyphicon glyphicon-log-in"></span> 登录
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <div class="row J_mainContent" id="content-main">
        <iframe id="J_iframe" width="100%" height="100%" seamless></iframe>
      </div>
    </div>
    <!--Right Navigation End-->
  </div>
</body>
{% endblock %}

frontend_backend_projects/django_project/homework/project/templates/project/login.html
{% extends "project/base.html" %} {% block content %}
<body class="gray-bg">
  <div class="middle-box text-center loginscreen  animated fadeInDown">
    <div>
      <div>
        <h1 class="logo-name">&nbsp;</h1>
      </div>
      <h3>欢迎登录!</h3>
      <form class="m-t" role="form" method="post" action="">
        {% csrf_token %}
        <div class="form-group">
          <input
            type="text"
            class="form-control"
            placeholder="用户名"
            required=""
            id="username"
            name="username"
          />
        </div>
        <div class="form-group">
          <input
            type="password"
            class="form-control"
            placeholder="密码"
            required=""
            id="password"
            name="password"
          />
        </div>
        <button type="submit" class="btn btn-primary block full-width m-b">
          登录
        </button>
        <p class="text-muted text-center">
          <a href="{% url 'project:register' %}">注册一个新的账户</a>
        </p>
      </form>
    </div>
  </div>
</body>
{% endblock %}

frontend_backend_projects/django_project/homework/project/templates/project/profile.html
{% extends "project/base.html" %}
{% load static %}
{% block content %}
<body class="gray-bg">
    <div class="wrapper wrapper-content">
        <div class="row animated fadeInRight">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>个人资料</h5>
                    </div>
                    <div>
                        <div class="ibox-content no-padding border-left-right" align="center">
                            <a class="" href="#" title="">
                                <img alt="image" class="img-responsive" src="{% static '/img/p_big2.jpg' %}" >
                            </a>
                        </div>
                        <div class="ibox-content profile-content">
                            <h4><strong>姓名：{{ user.role.student.name }}{{ user.role.teacher.name }}</strong></h4>
                            <h4>用户名: {{ user.username }}</h4>
                            <h4>Email: {{ user.email }} </h4>
                            <p><i class="fa fa-map-marker"></i> 北京市XXXXXX</p>
                            <h5>自我描述</h5>
                            <p>
                                会点前端技术，div+css啊，jQuery之类的，不是很精；热爱生活，热爱互联网，热爱新技术；有一个小的团队，在不断的寻求新的突破。
                            </p>
                            <p>
                                <ul>
                                    {% if request.user.role.role == 1 %}
                                        {% if request.user.role.teacher.gender %}
                                            <li>性别: 女 </li>
                                        {% else %}
                                            <li>性别: 男 </li>
                                        {% endif %}
                                    {% else %}
                                        {% if request.user.role.student.gender %}
                                            <li>性别: 女 </li>
                                        {% else %}
                                            <li>性别: 男 </li>
                                        {% endif %}
                                    {% endif %}
                                    {% if request.user.role.role == 1 %}
                                        <li>用户类型：教师 </li>
                                    {% else %}
                                        <li>用户类型：学生 </li>
                                    {% endif %}
                                    {% if user.role.role == 1 %}
                                    <li>职称: {{ user.role.teacher.ranks }} </li>
                                    {% else %}
                                    <li>班级: {{ user.role.student.classes }} </li>
                                    {% endif %}
                                </ul>
                            </p>
                            <div class="row m-t-lg">
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-4">
                                </div>
                            </div>
                            <div class="user-button">
                                <div class="row">
                                    <div class="col-sm-6">
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'project:profile_update' user.id %}">
                                            <button type="button" class="btn btn-primary btn-sm btn-block">
                                              <i class="fa fa-envelope"></i> 编辑信息
                                            </button>
                                        </a>
                                        {% endif %}
                                    </div>
                                    <div class="col-sm-6">
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'project:pwd_change' user.id %}">
                                            <button type="button" class="btn btn-default btn-sm btn-block">
                                              <span class="glyphicon glyphicon-wrench"> </span> 修改密码
                                            </button>
                                        </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>
</body>
{% endblock %}

frontend_backend_projects/django_project/homework/project/templates/project/profile_update.html
{% extends "project/base.html" %}
{% load static %}
{% block content %}
<body class="gray-bg">
    <div class="wrapper wrapper-content">
        <div class="row animated fadeInRight">
            <div class="col-sm-3"></div>
            <div class="col-sm-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>编辑资料</h5>
                    </div>
                    <div>
                        <div class="ibox-content no-padding border-left-right">
                            <img alt="image" class="img-responsive" src="{% static '/img/p_big2.jpg' %}">
                        </div>
                        <div class="ibox-content profile-content" align="center">
                                <h2>修改个人信息</h2>
                                <div class="form-wrapper">
                                    <form method="post" action="" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {% for field in form %}
                                            <div class="fieldWrapper">
                                        {{ field.errors }}
                                        <div class="row">
                                            <div class="col-sm-2"></div>
                                            <div class="col-sm-2">{{ field.label_tag }} </div>
                                            <div class="col-sm-2">{{ field }}</div>
                                        </div>
                                        {% if field.help_text %}
                                            <p class="help">{{ field.help_text|safe }}</p>
                                        {% endif %}
                                            </div>
                                        {% endfor %}
                                        <div >&nbsp;</div>
                                        <div class="form-group">
                                            <div class="col-md-4"></div>
                                            <div class="col-md-5">
                                                <input type="submit" class="btn btn-block btn-primary compose-mail" value="提交">
                                            </div>
                                        </div>
                                        <div >&nbsp;</div>
                                    </form>
                                </div>
                            </p>
                            <div class="row m-t-lg">
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-4">
                                </div>
                            </div>
                            <div class="user-button">
                                <div class="row">
                                    <div class="col-sm-6">
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'project:pwd_change' user.id %}">
                                            <button type="button" class="btn btn-default btn-sm btn-block">
                                              <span class="glyphicon glyphicon-wrench"> </span>  修改密码
                                            </button>
                                        </a>
                                        {% endif %}
                                    </div>
                                    <div class="col-sm-6">
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'project:logout' %}">
                                            <button type="button" class="btn btn-primary btn-sm btn-block">
                                              <span class="glyphicon glyphicon-log-out" ></span>  退出登录
                                            </button>
                                        </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>
</body>
{% endblock %}

frontend_backend_projects/django_project/homework/project/templates/project/pwd_change.html
{% extends "project/base.html" %} {% load static %} {% block content %}
<body class="gray-bg">
  <div class="wrapper wrapper-content">
    <div class="row animated fadeInRight">
      <div class="col-sm-3"></div>
      <div class="col-sm-6">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>修改密码</h5>
          </div>
          <div>
            <div class="ibox-content no-padding border-left-right">
              <img
                alt="image"
                class="img-responsive"
                src="{% static '/img/p_big2.jpg' %}"
              />
            </div>
            <div class="ibox-content profile-content">
              <h4><strong>用户名: {{ user.username }}</strong></h4>
              <h4>Email: {{ user.email }}</h4>
              <div class="row m-t-lg">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                  {% if message %} {{ message }} {% endif %}
                  <form method="post" action="" enctype="multipart/form-data">
                    <div class="form-group">
                      {% csrf_token %} 
                      {% for field in form %} {{ field.errors }}
                      <div class="col-sm-12">
                        {{ field.label_tag }} &nbsp; &nbsp;{{ field }}
                      </div>
                      {% if field.help_text %}
                      <span class="help-block m-b-none"
                        >{{ field.help_text|safe }}</span
                      >
                      {% endif %} {% endfor %}
                    </div>
                    <div>&nbsp;</div>
                    <div class="form-group">
                      <div class="col-md-2"></div>
                      <div class="col-md-6">
                        <input
                          type="submit"
                          class="btn btn-block btn-primary compose-mail"
                          value="提交"
                        />
                      </div>
                    </div>
                  </form>
                </div>
              </div>
              <div class="row m-t-lg">
                <div class="col-sm-4"></div>
                <div class="col-sm-4"></div>
                <div class="col-sm-4"></div>
              </div>
              <div class="user-button">
                <div class="row">
                  <div class="col-sm-6">
                    {% if user.is_authenticated %}
                    <a href="{% url 'project:profile' user.id %}">
                      <button
                        type="button"
                        class="btn btn-primary btn-sm btn-block"
                      >
                        <i class="fa fa-envelope"></i> 查看信息
                      </button>
                    </a>
                    {% endif %}
                  </div>
                  <div class="col-sm-6">
                    {% if user.is_authenticated %}
                    <a href="{% url 'project:logout' %}">
                      <button
                        type="button"
                        class="btn btn-default btn-sm btn-block"
                      >
                        <span class="glyphicon glyphicon-log-out"></span>
                        退出登录
                      </button>
                    </a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-3"></div>
    </div>
  </div>
</body>
{% endblock %}

frontend_backend_projects/django_project/homework/project/templates/project/register.html
{% extends "project/base.html" %} 
{% block content %}
<body class="gray-bg">
  <div class="middle-box text-center loginscreen   animated fadeInDown">
    <div>
      <div>
        <h1 class="logo-name">&nbsp;</h1>
      </div>
      <h3>欢迎注册！</h3>
      <form class="m-t" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %} {% for field in form %}
        <div class="form-group">
          {{ field.errors }}
          <!--{{ field.label_tag }} forms.py 中的提示标签 label-->
          {{ field }} {% if field.help_text %}
          <p class="help">{{ field.help_text|safe }}</p>
          {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary block full-width m-b">
          注册
        </button>
      </form>
    </div>
  </div>
</body>
{% endblock %}